sudo: required
dist: xenial

# stages:
#   - test
#   - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix js
  - lix run travix flash
  - lix run travix java
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php
  - lix run travix lua
